version: '3.8'
services:
  database:
    image: postgres:12.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: Gima99295
    ports:
      - 5432

  clickhouse:
    image: yandex/clickhouse-server:latest
    volumes:
      - clickhouse:/yandex/clickhouse-server:delegated
    ports:
      - 8123
      - 9000
      - 9004

  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    stdin_open: true
    tty: true
    command: bundle exec rackup -o 0.0.0.0 -p 3000 -s Puma
    depends_on:
      - database
      - clickhouse
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:delegated
    environment:
      - RACK_ENV=${RACK_ENV:-development}
      - DATABASE_URL=postgres://postgres:Gima99295@database:5432
      - CLICKHOUSE_URL=http://clickhouse:8123

volumes:
  bundle:
  postgres:
  clickhouse:
