version: '3.8'
services:
  database:
    build:
      context: ./clickhouse/
      dockerfile:
    volumes:
      - database:/yandex/clickhouse-server:delegated
    ports:
      - 8123
      - 9000
      - 9004

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: bundle exec rackup -o 0.0.0.0 -p 3000 -s Puma
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:delegated
    environment:
      - RACK_ENV=${RACK_ENV:-development}
      - DATABASE_URL=mysql2://default@database:9004

volumes:
  bundle:
  database:
