version: '3.8'
services:
  database:
    image: postgres:12.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: Gima99295
    ports:
      - 5432

  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    stdin_open: true
    tty: true
    command: bundle exec iodine -t 16 -w 4 -b 0.0.0.0 -p 3000
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:delegated
    environment:
      - RACK_ENV=${RACK_ENV:-development}
      - DATABASE_URL=postgres://postgres:Gima99295@database:5432
      - PGPASSWORD=Gima99295

volumes:
  bundle:
  postgres:
